"""recreate agents and memories tables"""     

revision = "d91b9b509159"
down_revision = "5d409935a6ee"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='agents_pkey')
    )
    op.create_index('ix_agents_id', 'agents', ['id'], unique=False)
    op.create_index('ix_agents_name', 'agents', ['name'], unique=False)
    op.create_index('ix_agents_role', 'agents', ['role'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.GUID(), nullable=False),
    sa.Column('agent_id', sa.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='memories_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memories')
    op.drop_index('ix_agents_id', table_name='agents')
    op.drop_index('ix_agents_name', table_name='agents')
    op.drop_index('ix_agents_role', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###


